version: 2
updates:
  - package-ecosystem: "cargo"
    directories:
      - "/Build"
      - "/adapters/rust"
      - "/Demo/wasm/rust"
      - "/Demo/wasm/c"
      - "/Demo/wasm/cpp"
      - "/Demo/wasm/runtime"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directories:
      - "/Demo"
      - "/Docs"
      - "/adapters/typescript"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directories: 
      - "/adapters/python"
      - "/Demo/wasm/python"
    schedule:
      interval: "weekly"
