[package]
name = "saikuro-c-insight"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
saikuro-c = { path = "../../../Build/adapters/c", default-features = false, features = ["wasm"] }
wasm-bindgen = "0.2"

[build-dependencies]
cc = "1"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[patch.crates-io]
embassy-time = { git = "https://github.com/embassy-rs/embassy", rev = "73b44d7e867a371d0870a84624fea66a8b00f713" }
embassy-time-driver = { git = "https://github.com/embassy-rs/embassy", rev = "73b44d7e867a371d0870a84624fea66a8b00f713" }
embassy-time-queue-utils = { git = "https://github.com/embassy-rs/embassy", rev = "73b44d7e867a371d0870a84624fea66a8b00f713" }
