/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const start_c_provider: (a: number, b: number) => void;
export const saikuro_provider_new: (a: number) => number;
export const saikuro_provider_register_with_schema: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const saikuro_provider_serve: (a: number, b: number) => number;
export const saikuro_string_dup: (a: number) => number;
export const saikuro_channel_abort: (a: number) => number;
export const saikuro_channel_close: (a: number) => number;
export const saikuro_channel_free: (a: number) => void;
export const saikuro_channel_next_json: (a: number, b: number, c: number) => number;
export const saikuro_channel_send_json: (a: number, b: number) => number;
export const saikuro_client_batch_json: (a: number, b: number) => number;
export const saikuro_client_call_json: (a: number, b: number, c: number) => number;
export const saikuro_client_call_json_timeout: (a: number, b: number, c: number, d: number) => number;
export const saikuro_client_cast_json: (a: number, b: number, c: number) => number;
export const saikuro_client_channel_json: (a: number, b: number, c: number) => number;
export const saikuro_client_close: (a: number) => number;
export const saikuro_client_connect: (a: number) => number;
export const saikuro_client_free: (a: number) => void;
export const saikuro_client_log: (a: number, b: number, c: number, d: number, e: number) => number;
export const saikuro_client_resource_json: (a: number, b: number, c: number) => number;
export const saikuro_client_stream_json: (a: number, b: number, c: number) => number;
export const saikuro_last_error_message: () => number;
export const saikuro_provider_close: (a: number) => number;
export const saikuro_provider_free: (a: number) => void;
export const saikuro_provider_register: (a: number, b: number, c: number, d: number) => number;
export const saikuro_stream_free: (a: number) => void;
export const saikuro_stream_next_json: (a: number, b: number, c: number) => number;
export const saikuro_string_free: (a: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hfd5825652474b0dd: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h3c54f7852024f377: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3c54f7852024f377_2: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h28091d3f1a679a46: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3c54f7852024f377_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h88035bc6817b0979: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
