<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <InvariantGlobalization>true</InvariantGlobalization>
    <WasmEnableThreads>false</WasmEnableThreads>
    <WasmBuildNative>true</WasmBuildNative>
    <EnableSdkWorkloadRestore>false</EnableSdkWorkloadRestore>
    <!-- thank goodness the below flag exists, this fixes automatic dependency resolution 
         because GitHub Advanced Security [bot] is a bit silly -->
    <MSBuildEnableWorkloadResolver>false</MSBuildEnableWorkloadResolver>
    <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../../Build/adapters/csharp/Saikuro/src/Saikuro.csproj" />
  </ItemGroup>
</Project>
