/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const start_cpp_provider: (a: number, b: number) => void;
export const saikuro_provider_new: (a: number) => number;
export const saikuro_provider_register_with_schema: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const saikuro_provider_serve: (a: number, b: number) => number;
export const saikuro_string_dup: (a: number) => number;
export const saikuro_channel_abort: (a: number) => number;
export const saikuro_channel_close: (a: number) => number;
export const saikuro_channel_free: (a: number) => void;
export const saikuro_channel_next_json: (a: number, b: number, c: number) => number;
export const saikuro_channel_send_json: (a: number, b: number) => number;
export const saikuro_client_batch_json: (a: number, b: number) => number;
export const saikuro_client_call_json: (a: number, b: number, c: number) => number;
export const saikuro_client_call_json_timeout: (a: number, b: number, c: number, d: number) => number;
export const saikuro_client_cast_json: (a: number, b: number, c: number) => number;
export const saikuro_client_channel_json: (a: number, b: number, c: number) => number;
export const saikuro_client_close: (a: number) => number;
export const saikuro_client_connect: (a: number) => number;
export const saikuro_client_free: (a: number) => void;
export const saikuro_client_log: (a: number, b: number, c: number, d: number, e: number) => number;
export const saikuro_client_resource_json: (a: number, b: number, c: number) => number;
export const saikuro_client_stream_json: (a: number, b: number, c: number) => number;
export const saikuro_last_error_message: () => number;
export const saikuro_provider_close: (a: number) => number;
export const saikuro_provider_free: (a: number) => void;
export const saikuro_provider_register: (a: number, b: number, c: number, d: number) => number;
export const saikuro_stream_free: (a: number) => void;
export const saikuro_stream_next_json: (a: number, b: number, c: number) => number;
export const saikuro_string_free: (a: number) => void;
export const wasm_bindgen_2474f29060f80a46___convert__closures_____invoke___wasm_bindgen_2474f29060f80a46___JsValue__core_9b3796e30d99ddb7___result__Result_____wasm_bindgen_2474f29060f80a46___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_2474f29060f80a46___convert__closures_____invoke___web_sys_47430de0600c93a4___features__gen_CloseEvent__CloseEvent______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_2474f29060f80a46___convert__closures_____invoke___web_sys_47430de0600c93a4___features__gen_CloseEvent__CloseEvent______true__2: (a: number, b: number, c: any) => void;
export const wasm_bindgen_2474f29060f80a46___convert__closures_____invoke___web_sys_47430de0600c93a4___features__gen_Event__Event______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_2474f29060f80a46___convert__closures_____invoke___web_sys_47430de0600c93a4___features__gen_CloseEvent__CloseEvent______true__4: (a: number, b: number, c: any) => void;
export const wasm_bindgen_2474f29060f80a46___convert__closures_____invoke_______true_: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
