# Deploy the static web demo to GH Pages.
name: GitHub Pages

on:
  push:
    branches: ["main"]
    paths:
      - "Demo/**"
      - "Docs/**"
      - "Build/adapters/**"
      - "Build/crates/**"
      - "tools/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "Justfile"
      - "Justfile.d"
      - ".github/workflows/static.yml"
  pull_request:
    paths:
      - "Demo/**"
      - "Docs/**"
      - "Build/adapters/**"
      - "Build/crates/**"
      - "tools/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "Justfile"
      - "Justfile.d"
      - ".github/workflows/static.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.98.1
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: Cargo.toml
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.0"
      - name: Setup xtask deps
        run: cargo xtask setup
      - name: Setup TypeScript adapter
        run: cargo xtask lang type-script setup
      - name: Setup demo app
        run: cargo xtask lang demo setup
      - name: Build TypeScript adapter
        run: cargo xtask lang type-script build
      - name: Setup Emscripten
        uses: myMindstorm/setup-emsdk@v14
        with:
          version: 3.1.64
      - name: Install .NET WASM workload
        run: sudo dotnet workload install wasm-tools
      - name: Build web demo
        run: cargo xtask lang demo build
      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v5
      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: Demo/dist

  deploy:
    name: Deploy demo to Pages
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
